# Cloud Build configuration for deploying static website
steps:
  # Step 1: Install pnpm and dependencies
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g pnpm
        pnpm install
    id: 'setup-dependencies'

  # Step 2: Set NODE_ENV to production for build
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g pnpm
        export NODE_ENV=production
        # Ensure public directory exists
        mkdir -p public
        # Copy necessary files to public
        cp index.html public/
        cp script.js public/
        cp styles.css public/
        cp IMG_1542.jpeg public/
        # Start server briefly to generate env.js
        pnpm start &
        sleep 5
        kill $!
        # Log status
        ls -la public/
    id: 'build-project'
    waitFor: ['setup-dependencies']

  # Step 3: Access OpenWeatherMap API Key from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        API_KEY=$$(gcloud secrets versions access latest --secret=openweathermap-api-key --project=jakoblangtry-com)
        echo "// Client-side environment variables
        const ENV = {
            OPENWEATHERMAP_API_KEY: '$${API_KEY}'
        };

        // Expose the environment to the window
        window.ENV = ENV;" > public/env.js
        # Verify env.js was created (without printing sensitive data)
        ls -la public/
    id: 'inject-api-key'
    waitFor: ['build-project']

  # Step 4: Copy static files to Cloud Storage bucket with explicit content types
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Copy HTML, JS, CSS files
        gsutil -m cp -r public/index.html gs://${_BUCKET_NAME}/
        gsutil -m cp -r public/script.js gs://${_BUCKET_NAME}/
        gsutil -m cp -r public/styles.css gs://${_BUCKET_NAME}/
        gsutil -m cp -r public/env.js gs://${_BUCKET_NAME}/
        
        # Copy image with explicit content type
        gsutil -h "Content-Type:image/jpeg" cp public/IMG_1542.jpeg gs://${_BUCKET_NAME}/
        
        # List bucket contents to verify
        gsutil ls -l gs://${_BUCKET_NAME}/
    id: 'deploy-files'
    waitFor: ['inject-api-key']

  # Step 5: Set Cache-Control headers for static assets
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'setmeta', '-h', 'Cache-Control:public, max-age=3600', 'gs://${_BUCKET_NAME}/**/*.html', 'gs://${_BUCKET_NAME}/**/*.css', 'gs://${_BUCKET_NAME}/**/*.js']
    id: 'set-cache-control'
    waitFor: ['deploy-files']

  # Step 6: Set Cache-Control headers for images
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Set cache for jpeg files - this will not fail if no files are found
        gsutil -m setmeta -h "Cache-Control:public, max-age=86400" gs://${_BUCKET_NAME}/**/*.jpeg 2>/dev/null || true
        
        # Set cache for jpg, png, gif if they exist (non-failing)
        gsutil -m setmeta -h "Cache-Control:public, max-age=86400" gs://${_BUCKET_NAME}/**/*.jpg 2>/dev/null || true
        gsutil -m setmeta -h "Cache-Control:public, max-age=86400" gs://${_BUCKET_NAME}/**/*.png 2>/dev/null || true
        gsutil -m setmeta -h "Cache-Control:public, max-age=86400" gs://${_BUCKET_NAME}/**/*.gif 2>/dev/null || true
    id: 'set-image-cache-control'
    waitFor: ['deploy-files']

  # Step 7: Set public read access
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['iam', 'ch', 'allUsers:objectViewer', 'gs://${_BUCKET_NAME}']
    id: 'set-public-access'
    waitFor: ['set-cache-control', 'set-image-cache-control']

  # Step 8: Verify deployment and check content types
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking content type of image file:"
        gsutil stat gs://${_BUCKET_NAME}/IMG_1542.jpeg
        
        echo "Listing all files in bucket:"
        gsutil ls -L gs://${_BUCKET_NAME}/
    id: 'verify-deployment'
    waitFor: ['set-public-access']

options:
   logging: CLOUD_LOGGING_ONLY

# Substitutions to be configured in Cloud Build trigger
substitutions:
  _BUCKET_NAME: 'jakoblangtry.com' # Bucket name for static website hosting

# Timeout for the entire build process
timeout: '600s'